### ISSUE TITLE
Generating from a `.opam` file?

### ISSUE THREAD

**Issue by poperigby** [josecastillolema/flatpak-opam-generator#2]
Haxe, in their infinite wisdom, have dependencies in their repository's [`haxe.opam`](https://github.com/HaxeFoundation/haxe/blob/development/haxe.opam) that aren't listed as dependencies for their opam package. Is there a way to generate the dependency tree for a `.opam` file?

**Comment by josecastillolema** [comment]
Hi!
Do you mean that `opam tree haxe` has missing dependencies?
If that's the case, my first recommendation would be to work with the haxe mantainers to fix them.
In the meantime, if there are not too many missing ones, why don't you manually add them to the generated dependency sources file?
Or do you need this as part of a CI where manual intervention is not doable?

**Comment by poperigby** [comment]
> Do you mean that opam tree haxe has missing dependencies?

Yeah. It looks like their latest opam release is 4.1.1, and their latest official release is 4.3.3. I'll try to get them to push the update then.

**Comment by poperigby** [comment]
I was able to make it work with:

```bash
opam pin add -k git -n haxe https://github.com/HaxeFoundation/haxe#4.3.3
opam tree --json=/tmp/haxe_deps.json haxe
```
